var _interopRequireDefault=require("@babel/runtime/helpers/interopRequireDefault");Object.defineProperty(exports,"__esModule",{value:true});exports.default=void 0;var _slicedToArray2=_interopRequireDefault(require("@babel/runtime/helpers/slicedToArray"));var _react=_interopRequireWildcard(require("react"));var _reactNative=require("react-native");var _reactNativeWebview=_interopRequireDefault(require("react-native-webview"));var _Container=_interopRequireDefault(require("../components/Container"));var _SanarKit=_interopRequireDefault(require("../SanarKit"));var _jsxRuntime=require("react/jsx-runtime");var _this=this,_jsxFileName="/Users/maren/Documents/medgulf/rnsdk/src/screens/SKChat.tsx";function _getRequireWildcardCache(e){if("function"!=typeof WeakMap)return null;var r=new WeakMap(),t=new WeakMap();return(_getRequireWildcardCache=function _getRequireWildcardCache(e){return e?t:r;})(e);}function _interopRequireWildcard(e,r){if(!r&&e&&e.__esModule)return e;if(null===e||"object"!=typeof e&&"function"!=typeof e)return{default:e};var t=_getRequireWildcardCache(r);if(t&&t.has(e))return t.get(e);var n={__proto__:null},a=Object.defineProperty&&Object.getOwnPropertyDescriptor;for(var u in e)if("default"!==u&&{}.hasOwnProperty.call(e,u)){var i=a?Object.getOwnPropertyDescriptor(e,u):null;i&&(i.get||i.set)?Object.defineProperty(n,u,i):n[u]=e[u];}return n.default=e,t&&t.set(e,n),n;}var _Dimensions$get=_reactNative.Dimensions.get('window'),width=_Dimensions$get.width,height=_Dimensions$get.height;var SKChat=function SKChat(props){var _useState=(0,_react.useState)(''),_useState2=(0,_slicedToArray2.default)(_useState,2),baseUrl=_useState2[0],setBaseUrl=_useState2[1];var appointmentId=props.appointmentId,empId=props.empId,enable=props.enable,onEndFlow=props.onEndFlow;var language=_reactNative.I18nManager.isRTL?'ar':'en';(0,_react.useEffect)(function(){if(enable){if(_SanarKit.default.session){var CHAT_URL=`${'http://192.168.1.146:9003/chat'}/${appointmentId}/${empId}?token=${_SanarKit.default.session.token}&lang=${language}`;if(!props.navigationOption){CHAT_URL=`${CHAT_URL}&nav=0`;}setBaseUrl(CHAT_URL);}else{console.warn('Not connected to Sanar Sarvices!');onEndFlow();}}},[enable]);var _onMessage=function onMessage(event){if(!event.canGoBack&&event.data&&event.data.includes('home')||event.canGoBack&&event.data&&event.data.includes('home')){setBaseUrl('');onEndFlow();}};if(!enable||!baseUrl){return null;}return(0,_jsxRuntime.jsx)(_Container.default,{children:(0,_jsxRuntime.jsx)(_reactNativeWebview.default,{source:{uri:baseUrl},style:{flex:1},onMessage:function onMessage(event){return _onMessage(event.nativeEvent);},injectedJavaScript:`
                (function() {
                    function wrap(fn) {
                    return function wrapper() {
                        var res = fn.apply(this, arguments);
                        window.ReactNativeWebView.postMessage(window.location.href);
                        return res;
                    }
                    }
                    history.pushState = wrap(history.pushState);
                    history.replaceState = wrap(history.replaceState);
                    history.go = wrap(history.go);
                    window.addEventListener('popstate', function() {
                        window.ReactNativeWebView.postMessage('navigationStateChange');
                    });
                })();
                true;
            `})});};var _default=exports.default=SKChat;var styles=_reactNative.StyleSheet.create({container:{flex:1,height:height,width:width,marginTop:25,marginBottom:30}});